/**
 * Zaeli Tutor — AI Summary Generation
 * lib/tutor-summaries.ts
 *
 * Two types of summaries, both generated by Sonnet:
 *
 * 1. Session summary — generated when a session ends
 *    Reads the full transcript, produces 2-3 sentence parent-facing summary.
 *
 * 2. Subject summary — generated on demand from Progress view
 *    Reads the last 5-10 session summaries for a subject, produces a
 *    progress narrative with trends, strengths, and focus areas.
 *
 * Summaries are cached in Supabase to avoid regeneration.
 */

import { supabase } from './supabase';
import { callClaude } from './api-logger';

const FAMILY_ID = '00000000-0000-0000-0000-000000000001';
const SONNET = 'claude-sonnet-4-6';

// ══════════════════════════════════════════════════
// SESSION SUMMARY — auto-generated when session ends
// ══════════════════════════════════════════════════

export async function generateSessionSummary(sessionId: string): Promise<string | null> {
  try {
    // Load session metadata
    const { data: session } = await supabase
      .from('tutor_sessions')
      .select('child_name, pillar, subject, topic, difficulty_band, question_count, hints_used, duration_seconds')
      .eq('id', sessionId)
      .single();
    if (!session) return null;

    // Already has summary?
    const { data: existing } = await supabase
      .from('tutor_sessions')
      .select('summary')
      .eq('id', sessionId)
      .single();
    if (existing?.summary) return existing.summary;

    // Load transcript
    const { data: messages } = await supabase
      .from('tutor_messages')
      .select('role, content, message_type, hint_level')
      .eq('session_id', sessionId)
      .order('created_at', { ascending: true });

    if (!messages || messages.length < 2) return null;

    // Build condensed transcript for Sonnet (max ~30 messages to keep tokens low)
    const transcript = messages.slice(0, 30).map((m: any) => {
      const role = m.role === 'zaeli' ? 'Zaeli' : session.child_name;
      const hint = m.hint_level ? ` [Hint ${m.hint_level}]` : '';
      const photo = m.message_type === 'photo' ? ' [Photo uploaded]' : '';
      return `${role}: ${m.content}${hint}${photo}`;
    }).join('\n');

    const duration = session.duration_seconds ? `${Math.round(session.duration_seconds / 60)} minutes` : 'unknown duration';
    const hints = session.hints_used ?? 0;
    const questions = session.question_count ?? 0;

    const response = await callClaude({
      feature: 'tutor_session',
      familyId: FAMILY_ID,
      body: {
        model: SONNET,
        max_tokens: 300,
        system: `You are Zaeli, writing a brief session summary for a parent. Be warm, specific, and honest. Focus on what the child did well and where they need more practice. Never use asterisks or markdown. Plain text only. Keep it short — 3 sentences max. Put a blank line between each sentence so it's easy to scan.`,
        messages: [{
          role: 'user',
          content: `Write a parent-facing summary for this tutor session:

Child: ${session.child_name}
Subject: ${session.subject ?? 'General'}
Topic: ${session.topic ?? 'Mixed'}
Pillar: ${session.pillar}
Difficulty band: ${session.difficulty_band}
Duration: ${duration}
Questions: ${questions}
Hints used: ${hints}

Transcript:
${transcript}

Write a 2-3 sentence summary for the parent. Be specific about what was covered and how the child performed. Mention any struggles and achievements.`,
        }],
      },
    });

    const summary = response?.content?.[0]?.text?.trim() ?? null;

    if (summary) {
      // Save to Supabase
      await supabase
        .from('tutor_sessions')
        .update({ summary, summary_generated_at: new Date().toISOString() })
        .eq('id', sessionId);
    }

    return summary;
  } catch (e) {
    console.error('generateSessionSummary error:', e);
    return null;
  }
}


// ══════════════════════════════════════════════════
// SUBJECT SUMMARY — on-demand from Progress view
// ══════════════════════════════════════════════════

export async function generateSubjectSummary(childName: string, subject: string): Promise<string | null> {
  try {
    // Check cache first (valid for 24 hours)
    const { data: cached } = await supabase
      .from('tutor_subject_summaries')
      .select('summary, generated_at')
      .eq('family_id', FAMILY_ID)
      .eq('child_name', childName)
      .eq('subject', subject)
      .single();

    if (cached?.summary) {
      const age = Date.now() - new Date(cached.generated_at).getTime();
      if (age < 24 * 60 * 60 * 1000) return cached.summary; // Fresh enough
    }

    // Load recent sessions for this subject
    const { data: sessions } = await supabase
      .from('tutor_sessions')
      .select('subject, topic, difficulty_band, question_count, hints_used, duration_seconds, summary, created_at')
      .eq('family_id', FAMILY_ID)
      .eq('child_name', childName)
      .eq('subject', subject)
      .order('created_at', { ascending: false })
      .limit(10);

    if (!sessions || sessions.length === 0) return null;

    // Build session digest
    const totalSessions = sessions.length;
    const totalMins = Math.round(sessions.reduce((sum: number, s: any) => sum + (s.duration_seconds ?? 0), 0) / 60);
    const totalHints = sessions.reduce((sum: number, s: any) => sum + (s.hints_used ?? 0), 0);
    const totalQuestions = sessions.reduce((sum: number, s: any) => sum + (s.question_count ?? 0), 0);
    const bands = sessions.map((s: any) => s.difficulty_band).filter(Boolean);
    const latestBand = bands[0] ?? 'core';
    const topics = [...new Set(sessions.map((s: any) => s.topic).filter((t: any) => t && t !== 'Zaeli picks'))];

    const sessionDigest = sessions.map((s: any) => {
      const when = new Date(s.created_at).toLocaleDateString('en-AU', { day: 'numeric', month: 'short' });
      return `${when}: ${s.topic ?? 'General'} — ${s.difficulty_band} band, ${s.hints_used ?? 0} hints, ${s.question_count ?? 0} questions${s.summary ? '. Summary: ' + s.summary : ''}`;
    }).join('\n');

    // Get child's year level from family_members
    const { data: memberData } = await supabase
      .from('family_members')
      .select('year_level')
      .eq('family_id', FAMILY_ID)
      .eq('name', childName)
      .single();
    const yearLevel = memberData?.year_level ?? 4;

    const response = await callClaude({
      feature: 'tutor_session',
      familyId: FAMILY_ID,
      body: {
        model: SONNET,
        max_tokens: 400,
        system: `You are Zaeli, writing a subject progress report for a parent. Be warm, specific, constructive, and honest. Celebrate genuine achievements. Be direct about areas needing work. Never use asterisks or markdown. Plain text only. Australian English. Write 3-4 short paragraphs (1-2 sentences each). Put a blank line between each paragraph so it's easy to scan. Keep the total under 80 words.`,
        messages: [{
          role: 'user',
          content: `Write a progress report for this child's ${subject} learning:

Child: ${childName}, Year ${yearLevel}
Subject: ${subject}
Total sessions (last 30 days): ${totalSessions}
Total time: ${totalMins} minutes
Total questions: ${totalQuestions}
Total hints used: ${totalHints}
Current difficulty band: ${latestBand}
Topics covered: ${topics.join(', ') || 'Various'}

Session history:
${sessionDigest}

Write a 3-5 sentence progress report for the parent. Include:
- Overall trajectory (improving, consistent, needs attention)
- Specific strengths observed
- Areas to focus on next
- A recommendation for what to practise next session`,
        }],
      },
    });

    const summary = response?.content?.[0]?.text?.trim() ?? null;

    if (summary) {
      // Upsert to cache
      await supabase
        .from('tutor_subject_summaries')
        .upsert({
          family_id: FAMILY_ID,
          child_name: childName,
          subject,
          summary,
          generated_at: new Date().toISOString(),
        }, { onConflict: 'family_id,child_name,subject' });
    }

    return summary;
  } catch (e) {
    console.error('generateSubjectSummary error:', e);
    return null;
  }
}
